<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* app.getflywheel.com/help.                                                       */
/***********************************************************************************/

defined('WP_CONTENT_DIR') or define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/wp-content' );

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'https://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  250);
define('WP_MEMORY_LIMIT', '128M');

define('FW_EVENT_ENABLED', true);
define('FW_HOME_PURGE', false);



/****************************************************************************/
/*                           Domain Configuration                           */
/****************************************************************************/

if ( !(defined('WP_CLI') && WP_CLI) ) {
    define('WP_SITEURL', FLYWHEEL_DEFAULT_PROTOCOL . 'magnoliastateconstruction.com');
    define('WP_HOME', FLYWHEEL_DEFAULT_PROTOCOL . 'magnoliastateconstruction.com');
}




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db7317721818');
define('DB_USER', 'fw4715096240');
define('DB_PASSWORD', 'zdHVJS7rUYg8mMZ8K4GWb5lplyhnAL');
define('DB_HOST', '192.168.23.92');

define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

$table_prefix  = 'wp_rqnm88bppt_';









/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          '@d9K|ct5}rutsy{TV)M8yVZf9B[fA&}*l),Y:Lx#OEJAwxAyzN(cUBo)~,AFmt|*');
define('SECURE_AUTH_KEY',   '6.Xez7u:v7#sef5oH&$NfQ23M;Ge-0GMR5{yh>Sr,uAUiETW/H/B9s|P!5&m3%Fw');
define('LOGGED_IN_KEY',     'D4MFFPqtQ`#QY@N**clZ!6K[gp=jn@shwPnKpfJuQW{k8SDc9}*V&sy>?@_%::s$');
define('NONCE_KEY',         'OF`R<A<]dblIqeG3:U7c6qntg[jw=/q0k99Nr@7./j_K{bTu/m9,I}sh3n*)zmMP');
define('AUTH_SALT',         'hyIr0=sZrVt|mVJ*lK,FI,@d^@8B|.@U4}>@<<sm:M0(fu6/UK+<im>)U[cSa}6@');
define('SECURE_AUTH_SALT',  '^p^n=dCO/$n;JRuWBVF&60LAFW/W,hV}L6BkBl6`iwSx,5vIWMj`_=s*=mBO6@HJ');
define('LOGGED_IN_SALT',    '30]R>3Pd8r9vFgaGD$/!sH(nKJmP=:J_er#f1qaw&Ex)mql/^PN4cl>/IH-]4Ko}');
define('NONCE_SALT',        'H(J<FA#1J8^mDoo]38oJBbD/tZw|^9kB7%+cvN4BwO]@FWQ$)fejae)-^>`b)T~H');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/

define('WPLANG', '');


define('WP_DEBUG', false);

define('WP_CACHE', true);






/****************************************************************************/
/*              WordPress Real Time Collaboration Configuration             */
/****************************************************************************/
define('WPE_DATACENTER', 'northamerica');
define('FW_WPE_APIKEY', '0e3d437e43ab3c148336797796e4e18a16f0fe1b');
define('FW_PWP_HASH', '8icj7cotu4');





/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);

/****************************************************************************/
/*                    Flywheel NextGen Gallery Support                      */
/****************************************************************************/
define('NGG_GALLERY_ROOT_TYPE', 'content');


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/.wordpress/');

if ( !empty( $_SERVER['HTTP_FASTLY_SSL'] ) || ( !empty( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && ( $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' ) ) )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
